/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
multiplicacion_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
division_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}
