/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct suma_1_argument {
	float arg1;
	float arg2;
};
typedef struct suma_1_argument suma_1_argument;

struct resta_1_argument {
	float arg1;
	float arg2;
};
typedef struct resta_1_argument resta_1_argument;

struct multiplicacion_1_argument {
	float arg1;
	float arg2;
};
typedef struct multiplicacion_1_argument multiplicacion_1_argument;

struct division_1_argument {
	float arg1;
	float arg2;
};
typedef struct division_1_argument division_1_argument;

#define CALCPROG 0x20000199
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  float * suma_1(float , float , CLIENT *);
extern  float * suma_1_svc(float , float , struct svc_req *);
#define RESTA 2
extern  float * resta_1(float , float , CLIENT *);
extern  float * resta_1_svc(float , float , struct svc_req *);
#define MULTIPLICACION 3
extern  float * multiplicacion_1(float , float , CLIENT *);
extern  float * multiplicacion_1_svc(float , float , struct svc_req *);
#define DIVISION 4
extern  float * division_1(float , float , CLIENT *);
extern  float * division_1_svc(float , float , struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define RESTA 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define MULTIPLICACION 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_suma_1_argument (XDR *, suma_1_argument*);
extern  bool_t xdr_resta_1_argument (XDR *, resta_1_argument*);
extern  bool_t xdr_multiplicacion_1_argument (XDR *, multiplicacion_1_argument*);
extern  bool_t xdr_division_1_argument (XDR *, division_1_argument*);

#else /* K&R C */
extern bool_t xdr_suma_1_argument ();
extern bool_t xdr_resta_1_argument ();
extern bool_t xdr_multiplicacion_1_argument ();
extern bool_t xdr_division_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
