/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>

float * suma_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 + arg2;

	return &result;
}

float * resta_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 - arg2;

	return &result;
}

float * multiplicacion_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1 * arg2;

	return &result;
}

float * division_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	if(arg2 == 0){
		printf("Error: No se puede dividir por 0\n");
		result = 0.0;
	}
	else{
		result = arg1 / arg2;
	}

	return &result;
}
