/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>

void calculadora (char *host, float arg1, char op, float arg2){
	CLIENT *clnt;
	float  *result = NULL;
	
	clnt = clnt_create(host, CALCPROG, CALCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	switch (op){ // Selecciona la operacion a realizar
		case '+':
			result = suma_1(arg1, arg2, clnt);
			break;
		case '-':
			result = resta_1(arg1, arg2, clnt);
			break;
		case '*':
			result = multiplicacion_1(arg1, arg2, clnt);
			break;
		case '/':
			result = division_1(arg1, arg2, clnt);
			break;
		default:
			printf("Operador invalido\n");
			clnt_destroy(clnt);
			break;
	}

	if(result == NULL){
		clnt_perror(clnt, "Error en la llamada RPC");
	}
	else{
		printf("Resultado: %f\n", *result);
	}

}

int main (int argc, char *argv[]){
	
	if (argc != 5){
		printf ("Uso correcto: %s <host> <numero> <operador> <numero>\n", argv[0]);
		exit (1);
	}

	char *host = argv[1];
	float arg1 = atof(argv[2]);
    char op = argv[3][0];
    float arg2 = atof(argv[4]);

	calculadora(host, arg1, op, arg2);
	
	exit (0);
}
